### ISSUE TITLE
可能发现了一个BUG

### ISSUE THREAD

**Issue by BetterLuke** [serverless-components/tencent-cynosdb#9]
如果在腾讯云的web控制台手动修改root用户的密码，然后在本地开发环境，使用`sls info`查看的密码依然是修改密码前到，那么自然，后端服务基于此值无法正确连接到数据库。

如果你需要更多细节，请评论补充。

**Comment by yugasun** [comment]
@BetterLuke 组件帮忙创建数据库的密码只是用户没有配置时，随机生成的，而如果用户自己在控制台修改了，这里 serverless 是无法感知到的，也没法查询到，因为涉及到用户隐私信息。所以一旦用户在控制台自己创建了密码，请妥善保管。

**Comment by BetterLuke** [comment]
> @BetterLuke 组件帮忙创建数据库的密码只是用户没有配置时，随机生成的，而如果用户自己在控制台修改了，这里 serverless 是无法感知到的，也没法查询到，因为涉及到用户隐私信息。所以一旦用户在控制台自己创建了密码，请妥善保管。

真心感谢，问题已解决 💯 

---
此issue可以关闭啦~
